### ISSUE TITLE
AySearchTable，scrollX属性数据类型校验报错

### ISSUE THREAD

**Issue by fastLazy** [viewweiwu/amiya#100]
目前的数据类型是number,但是我传的是string效果是有的，下面截图是官网文档

![image](https://user-images.githubusercontent.com/19260808/221122652-aaaf4c81-7439-4f9e-ac07-5153ec2b4947.png)

**Comment by fastLazy** [comment]
![image](https://user-images.githubusercontent.com/19260808/221122974-48dc56ee-2350-4b40-9016-c3ccd1347ace.png)

**Comment by viewweiwu** [comment]
看来是官网更新了文档，不影响使用的话，随后我再不一下

**Comment by fastLazy** [comment]
恩，不影响使用
