### ISSUE TITLE
AySearchList 卡片布局 & tag 查询

### ISSUE THREAD

**Issue by ywzhaiqi** [viewweiwu/amiya#109]
AySearchList 卡片布局 & tag 查询的示例中，添加了一个按钮，用于 设置 tag 的值（如下）
```jsx
 <Button type="primary" onClick={() => setTag("狙击")}>
        设置狙击
</Button>
```
点击后， `角色职业` 这列 还是 `全部`，而非 `狙击`。怎么让 `角色职业` search 列 随之变动？
具体 demo：
https://codesandbox.io/s/amiya-list-settag-4ld0uu?file=/App.tsx:5228-5314

**Comment by viewweiwu** [comment]
因为顶部本身是一个 form，所以需要自己往 form 里面塞值
```
<Button
  type="primary"
  onClick={() => {
    listRef.current.getSearchRef().setFieldsValue({ class: "医疗" });
    listRef.current.getSearchRef().submit();
  }}
>
  设置狙击
</Button>
```
