### ISSUE TITLE
aySearchTable去除扩展表格别名功能，或者可配置隐藏

### ISSUE THREAD

**Issue by a758801405** [viewweiwu/amiya#19]
v0.8.2
![image](https://user-images.githubusercontent.com/13042895/99921412-33446800-2d65-11eb-8388-d5edfd96cb37.png)

**Comment by viewweiwu** [comment]
请尝试用 css 隐藏
.ay-search-table-extra-fields-edit-line-right .ant-input-affix-wrapper { display: none; }
