### ISSUE TITLE
aySearchTable增加远程排序和筛选功能

### ISSUE THREAD

**Issue by a758801405** [viewweiwu/amiya#20]
v0.8.2
![image](https://user-images.githubusercontent.com/13042895/99921529-eb721080-2d65-11eb-8ddb-c5ccb2833f51.png)

**Comment by viewweiwu** [comment]
默认就是远程的，请查看表格的返回参数。看文档
http://viewweiwu.gitee.io/amiya/table/%E7%AD%9B%E9%80%89%E4%B8%8E%E6%8E%92%E5%BA%8F
