### ISSUE TITLE
AySearchTable在左侧有内容时，全屏再还原后宽度异常

### ISSUE THREAD

**Issue by a758801405** [viewweiwu/amiya#36]
![image](https://user-images.githubusercontent.com/13042895/103347456-099ffe80-4ad2-11eb-846a-c688b84ff002.png)
v0.14.2

**Comment by viewweiwu** [comment]
flex 会导致容器宽度不确定。

给父容器设置 `overflow: hidden`。

```html
<div style="overflow: hidden">
    <AySearchTable />
</div>
```
