### ISSUE TITLE
aySearchTable  filter  怎么默认某个筛选条件

### ISSUE THREAD

**Issue by a758801405** [viewweiwu/amiya#53]
![image](https://user-images.githubusercontent.com/13042895/116338953-2bef2200-a80f-11eb-850d-a42588dba87b.png)
amiya v0.19.1

**Comment by viewweiwu** [comment]
目前还没有支持，会考虑安排

**Comment by a758801405** [comment]
![image](https://user-images.githubusercontent.com/13042895/116339703-7a50f080-a810-11eb-8790-b2e51087ba33.png)
antd有个filteredValue和defaultFilterValue 有空支持下

**Comment by viewweiwu** [comment]
v0.20.0 已经添加对应方法。

```js
{
   defaultFilterValue: 'xxx'
}
```
http://viewweiwu.gitee.io/amiya/table/%E7%AD%9B%E9%80%89%E4%B8%8E%E6%8E%92%E5%BA%8F#%E9%BB%98%E8%AE%A4%E5%80%BC
