### ISSUE TITLE
aySearchTable点击重置时，把filter也清空掉

### ISSUE THREAD

**Issue by a758801405** [viewweiwu/amiya#56]
amiya: v0.20.0

**Comment by viewweiwu** [comment]
v0.23.0

```html
<AySearchTable searchExtend={{ onReset: () => tableRef.current. clearFilters() }} />
```

![image](https://user-images.githubusercontent.com/14287892/123588351-341d0b00-d81a-11eb-8014-cd18c0d8d467.png)
