### ISSUE TITLE
请问一下，文档组件样式是怎么样加上去的，我看到你文档也没有引入相关的样式文件

### ISSUE THREAD

**Issue by qc-z** [viewweiwu/amiya#67]

**Comment by viewweiwu** [comment]
文档在全局家了，所以有样式。
https://github.com/viewweiwu/amiya/blob/master/.dumi/theme/builtins/Previewer.tsx#L22

**Comment by qc-z** [comment]
> 文档在全局加了，所以有样式。 https://github.com/viewweiwu/amiya/blob/master/.dumi/theme/builtins/Previewer.tsx#L22

请教一下，如果不自定义主题，应该在哪引入

**Comment by qc-z** [comment]
我在.umirc.ts配置了extraBabelPlugins，分别是antd样式的按需加载和我自己的按需加载，但是我写的样式被覆盖了
![image](https://user-images.githubusercontent.com/22362903/177482670-acdee434-b609-4d8c-8985-cb5c08991c8e.png)
![image](https://user-images.githubusercontent.com/22362903/177483183-9168d53c-3df5-4f99-8389-2f73b9d9b210.png)

**Comment by qc-z** [comment]
![image](https://user-images.githubusercontent.com/22362903/177483879-1404d153-e9fb-4ea4-889f-953273bbcbe2.png)

**Comment by viewweiwu** [comment]
不清楚，问问 dumi 吧
