### ISSUE TITLE
AyCard 中示例折叠无效

### ISSUE THREAD

**Issue by a758801405** [viewweiwu/amiya#68]
https://viewweiwu.gitee.io/amiya/components/ay-card

**Comment by viewweiwu** [comment]
是文档有问题，实际上是有效果的，可以看 https://viewweiwu.github.io/amiya/components/ay-card。
回头查一下 gitee 的问题

**Comment by viewweiwu** [comment]
gitee pages 要实名认证了，还是不用了
国内的可以改成访问这个
https://minisunflower.vip/amiya/
