### ISSUE TITLE
AySearchTable 在大量数据和多数据列的场景下怎么优雅的使用？

### ISSUE THREAD

**Issue by VincentYyyy** [viewweiwu/amiya#70]
主要组件：AySearchTable
示例描述：
1.是否支持”设置展示列“的当前设置缓存到本地，并在页面刷新时自动恢复上一次的设置？
2.是否能支持像antd表格那样的左右固定指定的列，并横向滚动其他的列？
3.或者有其他的做法？

附图：
![image](https://user-images.githubusercontent.com/46081815/185363092-e80d9ef6-e4e6-4e6b-b720-85da41c38f88.png)
**设置展示列**

![image](https://user-images.githubusercontent.com/46081815/185363769-444fb665-f66a-447d-a340-a2861c32e9aa.png)
**antd - table组件示例 - 固定头和列**

**Comment by viewweiwu** [comment]
存在本地其实会有点危险，如果将来维护你想要加一列，发现被缓存了，就会很痛苦。
如果你有这个需求，建议隐藏这个东西，然后自己实现一个。

**Comment by VincentYyyy** [comment]
合理
另外，我在源码看到了对antd table原接口的暴露，fiedls设置width、fix，结合AySearchTable的scrollX可以实现固定列效果
