### ISSUE TITLE
《求助》searchTable 鼠标指到表格就报错

### ISSUE THREAD

**Issue by Wang-yubo** [viewweiwu/amiya#71]
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/59524432/187066762-a19fdebc-2c03-49f7-80fb-ecfed3336429.png">
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/59524432/187066800-ac4e10ce-168d-41df-ba17-9ab6df282355.png">

**Comment by viewweiwu** [comment]
确实文档也出了问题，等我看下为什么

**Comment by viewweiwu** [comment]
cmd/ctrl + R 刷新下页面再看下
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/14287892/187067913-0e6ac150-f45b-44e3-ac21-f4cee41df389.png">

**Comment by Wang-yubo** [comment]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/59524432/187069136-d3c76965-101f-4c4e-871e-339831be514c.png">
新版也还是一样的报错，可编辑行和可编辑单元格都是鼠标指上去就报错了；

**Comment by Wang-yubo** [comment]
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/59524432/187076852-7ea33398-f442-4cb4-877c-3a4e2ffed157.png">
能解决吗？codesandbox打开也是鼠标指上去就报错。

**Comment by viewweiwu** [comment]
刚出去吃饭了，正在看

**Comment by viewweiwu** [comment]
已经修复，安装 0.57.1 尝试

**Comment by viewweiwu** [comment]
https://codesandbox.io/s/brave-hooks-mz6dle

**Comment by Wang-yubo** [comment]
可以了，多谢。

**Comment by viewweiwu** [comment]
关于注册的代码，尽量放在公共地方，这样全局引入一次就好了。
<img width="512" alt="image" src="https://user-images.githubusercontent.com/14287892/187335764-8890da77-c0bf-4df2-85a4-cdb6ba01e4df.png">
