### ISSUE TITLE
请问一下，可编辑表格 字段联动 怎么做?

### ISSUE THREAD

**Issue by Wang-yubo** [viewweiwu/amiya#72]
比如a字段的改变以后手动设置bz字段的值?没有找到对应的方法去做呢。而且可编辑表格好像不能使用render方法去设置字段

**Comment by viewweiwu** [comment]
暂时没有直接更改的方法，不过可以通过注册的方式把原本的类型覆盖一下。
可以这样写：

```tsx
// 注册
registerTableRender('editable-cell-input', ({ text, record, field }: RenderProps) => {
  return ({ editing, mode, save }: AnyKeyProps) => {
    // 保存前，看是否需要更改某个字段
    const beforeSave = () => {
      if (field.beforeSave) {
        field.beforeSave(record)
      }
      save()
    }
    return !editing ? text : <Input {...field.contentProps} onBlur={beforeSave} />
  }
})
// 使用
{
  title: '英文名',
  key: 'en',
  width: 100,
  editable: true,
  renderType: 'editable-cell-input',
  // 尝试更改字段
  beforeSave: (record) => {
    record.cn = record.cn + Date.now()
  }
},
```
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/14287892/187334217-21df7792-6447-410e-9ba0-2554a2d05891.png">

https://codesandbox.io/s/keen-ully-5k7v1m?file=/App.tsx:664-857

**Comment by viewweiwu** [comment]
注册文档：https://viewweiwu.github.io/amiya/components/table/edit-table#%E6%89%A9%E5%B1%95%E5%8F%AF%E7%BC%96%E8%BE%91%E7%B1%BB%E5%9E%8B

**Comment by viewweiwu** [comment]
关于注册的代码，尽量放在全局，这样只需要一次就可以了
<img width="512" alt="image" src="https://user-images.githubusercontent.com/14287892/187335854-c70ca021-32b3-41e2-89b1-3bf962ee2fbb.png">
