### ISSUE TITLE
如何配置 一个 自定义表单组件的 自定义校验 ？

### ISSUE THREAD

**Issue by huanlirui** [viewweiwu/amiya#74]
比如作者提供的这个示例https://viewweiwu.github.io/amiya/components/Global/register-field

大多数都是一个required 来 校验值是否空。

如果我是自定义注册的表单组件，如何配置自定义校验规则呢？rules这个参数，怎么和自定义组件配合 ？

**Comment by viewweiwu** [comment]
``` js

{
  key: 'loginName',
  required: true,
  maxLength: 11,
  rules: [{ message: '请输入正确的手机号', pattern: /^1\d{10}$/, validateTrigger: 'blur' }],
},
```

**Comment by huanlirui** [comment]
![image](https://user-images.githubusercontent.com/40491203/195793472-23fb8340-26f8-4fe4-a35e-322beea10afb.png)

**Comment by viewweiwu** [comment]
试试这样写

``` jsx

rules: [
    {
      message: '两次密码不一致',
      validator: (_: any, value: string) => {
        return new Promise((resolve, reject) => {
          if (value !== formRef.current.getFieldValue('password')) {
            reject();
          } else {
            resolve(value);
          }
        });
      },
    },
  ]
```

**Comment by huanlirui** [comment]
谢谢，是我自己的问题。生效了！

**Comment by huanlirui** [comment]
除了能够配置的 onChange, blur 等时机校验，是否有方法，能在第三方组件内，主动触发校验 ?

**Comment by viewweiwu** [comment]
formRef.current.submit()

**Comment by huanlirui** [comment]
> formRef.current.submit()

![image](https://user-images.githubusercontent.com/40491203/196085075-648d0075-74e7-4329-b9f8-f61718ce8364.png)
form表单是通过配置生成的，ref在哪里绑定？哪里能拿到....

**Comment by huanlirui** [comment]
> formRef.current.submit()

抱歉，我没描述清楚。form能拿到ref没毛病。如果我是使用amiya的表格，表单是通过配置项来生成的。ref如何拿呢？
![image](https://user-images.githubusercontent.com/40491203/196085662-a797aeb3-eb93-4050-8fbc-17a19ca72b05.png)

**Comment by viewweiwu** [comment]
尝试把 Ref 放在这里

```diff
<AySearchTable
    api={listApi}
    title="尝试点击【新增】【详情】【编辑】等按钮"
    ctrl={ctrl}
    fields={fields}
    rowKey="sort_id"
    dialogFormExtend={{
      fields,
      addApi,
  +   ref: formRef,
      updateApi
    }}
  >
```

**Comment by viewweiwu** [comment]
如果只是想要验证的话，方法都是一样的。submit 会提交
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/14287892/196093355-1d8479d6-e4f5-46e4-88d2-5649d0b82d92.png">

**Comment by huanlirui** [comment]
> 尝试把 Ref 放在这里
> 
> ```diff
> <AySearchTable
>     api={listApi}
>     title="尝试点击【新增】【详情】【编辑】等按钮"
>     ctrl={ctrl}
>     fields={fields}
>     rowKey="sort_id"
>     dialogFormExtend={{
>       fields,
>       addApi,
>   +   ref: formRef,
>       updateApi
>     }}
>   >
> ```

非常感谢解答！！amiya超好用!
