### ISSUE TITLE
数据为 嵌套结构，如何 配置默认值？

### ISSUE THREAD

**Issue by huanlirui** [viewweiwu/amiya#76]
作者大大你好，最近在深度使用您的库，看着文档，半猜半懵在配置，实在没解决这个如何配置，这个defaultValue如何设置初始值？我期望设置初始值为 一个嵌套的数据结构  CustomData.status   看下图👇

![image](https://user-images.githubusercontent.com/40491203/196626130-f48469c9-0549-40c0-be97-238f1497b05f.png)

**Comment by viewweiwu** [comment]
抱歉，因为内部结构复杂 key 暂时只支持 string 格式，可以在 beforeSubmit 的时候更改。

```js
{
  key: 'status',
}

const beforeSubmit = (params: FormValues) => {
  params.customData = { status: params.status }
  delete params.status
  return params
}

<AySearchTable
  dialogFormExtend={{
    fields: fields,
    updateApi,
    addApi,
    beforeSubmit
  }}
/>
```

**Comment by huanlirui** [comment]
![image](https://user-images.githubusercontent.com/40491203/196626313-4676b5ee-bac4-45d7-843c-4de4fc640ae4.png)
如图所示，在编辑的时候，dialog默认应该会回填表单信息，这个customData.status 是等于true的，但是switch 并不匹配
```
customData = {
     status : true
}

```

**Comment by viewweiwu** [comment]
塞数据的时候直接塞 status，不要前面的 customData。
form 只支持一层

**Comment by viewweiwu** [comment]
table 上展示是可以使用 dataIndex 的，form 的话不行

**Comment by viewweiwu** [comment]
看情况你需要这样处理，在 

```js
const ctrl: AyTableCtrlField = {
  render: (value: string, record: Record) => {
+   record = { ...record, ...record.customData }
    return (
      <AyCtrl>
        <AyAction record={record} action="update">
          编辑
        </AyAction>
        <AyAction record={record} action="delete">
          删除
        </AyAction>
      </AyCtrl>
    )
  }
}
```

**Comment by huanlirui** [comment]
> 看情况你需要这样处理，在得到 record 数据的时候把 customData 平铺一下
> 
> ```js
> const ctrl: AyTableCtrlField = {
>   render: (value: string, record: Record) => {
> +   record = { ...record, ...record.customData }
>     return (
>       <AyCtrl>
>         <AyAction record={record} action="update">
>           编辑
>         </AyAction>
>         <AyAction record={record} action="delete">
>           删除
>         </AyAction>
>       </AyCtrl>
>     )
>   }
> }
> ```

wow这个方案可以

**Comment by viewweiwu** [comment]
ok 能解决问题就好。
