### ISSUE TITLE
表单验证无法覆盖默认的

### ISSUE THREAD

**Issue by niyg** [viewweiwu/amiya#79]
![image](https://user-images.githubusercontent.com/14817820/198545870-2e0e3437-20f3-4193-843b-abf6dc9b1f14.png)
自定义表单项验证，但是默认的验证无法去除。
![image](https://user-images.githubusercontent.com/14817820/198546057-f3d07682-a1ab-4479-baf8-7c29260a85ec.png)

**Comment by niyg** [comment]
![image](https://user-images.githubusercontent.com/14817820/198552946-81c78b6d-92fb-4499-8866-633d2db48c00.png)
源码位置，这边是不是可以改成直接替换。提示语因为有可能并不是直接从lablel中取

**Comment by viewweiwu** [comment]
换一个写法，把这个删了就好了
<img width="951" alt="image" src="https://user-images.githubusercontent.com/14287892/198553578-f482dea7-e826-440b-84c4-c663487e42c4.png">
