### ISSUE TITLE
AySearchTable多选， 怎么手动控制的行数据？

### ISSUE THREAD

**Issue by fastLazy** [viewweiwu/amiya#83]
AySearchTable多选， 怎么手动控制的行数据？

`·rowSelection | 表格选项设置，可以用来设置表格是否禁用，请不要设置 type、selectedRowKeys、onSelect、onSelectAll 方法，这会影响到原本的设置。`

可以在rowSelection  里面设置吗？

**Comment by viewweiwu** [comment]
https://viewweiwu.github.io/amiya/components/table/selection-ctrl

**Comment by fastLazy** [comment]
好像不起作用啊，tableRef.current是undefined

**Comment by viewweiwu** [comment]
你是不是忘记了 <AySearchTable ref={tableRef} /> 这一步

**Comment by fastLazy** [comment]
> 你是不是忘记了 `<AySearchTable ref={tableRef} /> ` 这一步

做了的，没忘记

**Comment by fastLazy** [comment]
AySearchTable  是包在弹窗里面的

**Comment by viewweiwu** [comment]
放不放在弹窗影响不大，在于什么时候使用

**Comment by viewweiwu** [comment]
你是在什么时候使用的，此时表格渲染完成了没有

**Comment by fastLazy** [comment]
表格是放在自定义注册类型的组件里面

**Comment by viewweiwu** [comment]
可以看看是什么效果吗，截个图吗，我可以给给点建议，可能是什么流程什么问题
