### ISSUE TITLE
如何在表格外层获取编辑选中数据

### ISSUE THREAD

**Issue by niyg** [viewweiwu/amiya#85]
需求：
我需要在打开编辑弹窗的时候，获取到当前选中的那条数据，根据数据字段，判断哪些field隐藏。
![image](https://user-images.githubusercontent.com/14817820/200107162-120f7217-66d7-4f90-9a5f-8b247d8138df.png)

**Comment by viewweiwu** [comment]
```js
{
  // formValues 是当前表单的数据
   hidden: '{{ formValues.test === 1 }}'
}
```

**Comment by viewweiwu** [comment]
https://viewweiwu.github.io/amiya/components/form#%E8%A1%A8%E5%8D%95%E8%81%94%E5%8A%A8-%E8%A1%A8%E8%BE%BE%E5%BC%8F

**Comment by viewweiwu** [comment]
```
{
  key: 'name1',
  dialog: {
    hidden: true
  }
}

```

**Comment by niyg** [comment]
我刚看到，从AyAction onopen中也能获取到行数据。

**Comment by viewweiwu** [comment]
可以解决问题就行✌️
