### ISSUE TITLE
AySearchTable的fileds的type设置成custom以后，点编辑按钮第一次不会渲染数据

### ISSUE THREAD

**Issue by fastLazy** [viewweiwu/amiya#86]
整个编辑表单第一加载的时候不会渲染，是空的，第二次点击以后才会显示
```
{
  title: '所属地区',
  align: 'center',
  key: 'cn_area_fullpath',
  type: 'custom',
  dialog: {
    required: true,
    renderContent: (field: AyFormField, record: any) => <AreaSelectAll.Component />,
  },

  table: {
    render: (_: any, record: any) => record.cn_area?.merger_name.replaceAll(',', ' / '),
  },
},
```

**Comment by fastLazy** [comment]
报错信息：`index.js:248 Uncaught TypeError: Cannot read properties of undefined (reading 'setFieldsValue')`

**Comment by viewweiwu** [comment]
试着吧 <AreaSelectAll /> 换成默认 antd 的 <Input /> 看问题是不是还存在

**Comment by fastLazy** [comment]
改成自定义注册组件，也是同样的问题

**Comment by bigzhu** [comment]
> 试着吧 换成默认 antd 的 看问题是不是还存在

是 antd 的问题, 报错如下:

`Uncaught TypeError: Cannot read properties of undefined (reading 'setFieldsValue')
`
https://ant-design.gitee.io/components/form-cn/#%E4%B8%BA%E4%BD%95%E5%9C%A8-Modal-%E4%B8%AD%E8%B0%83%E7%94%A8-form-%E6%8E%A7%E5%88%B6%E5%8F%B0%E4%BC%9A%E6%8A%A5%E9%94%99%EF%BC%9F

作者试试给 Modal 设置一个 forceRender 确保引用存在.

**Comment by fastLazy** [comment]
@viewweiwu 坐等更新版本，哈哈

**Comment by viewweiwu** [comment]
能不能贴一个完整的，我好实验一下，我自己是没有遇到过不行的

**Comment by viewweiwu** [comment]
感觉应该不是 forceRender 的问题

**Comment by fastLazy** [comment]
@viewweiwu 
就是列表上点击编辑的时候，弹出的Modal表单，第一次会没有数据回填。
点击第二次的时候就会有数据
第一次没有数据回填的时候报错：`Uncaught TypeError: Cannot read properties of undefined (reading 'setFieldsValue')`

查了一下，问题应该是antd的Modal没有渲染，导致form回填数据报错。

所以加个forceRender 试试

**Comment by viewweiwu** [comment]
试着使用 0.57.5，尝试修复了下这个 bug ，使用 forceRender 太不优雅了。

**Comment by fastLazy** [comment]
> 

没事，你太棒了，既然官方都给了这个props那就用起来呗

**Comment by fastLazy** [comment]
排查了一下，好像不是amiya的问题，估计是我们项目有问题，哈哈，不好意思了，让你费心了

**Comment by fastLazy** [comment]
@viewweiwu 排查到问题了，哈哈，那个forceRender可以删除掉了。下次更新版本记得和我说 谢谢你，麻烦了

**Comment by fastLazy** [comment]
把依赖包删除了，重新安装依赖就解决问题了

**Comment by viewweiwu** [comment]
因为我已经复现出问题了，并不是 forceRender 的问题，所以发了个版本修好了。
能帮到你解决问题就 OK。

**Comment by fastLazy** [comment]
方便加个微信？哈哈，最近在用amiya开发项目

**Comment by viewweiwu** [comment]
可以的，就是这个 id

**Comment by fastLazy** [comment]
加你了
