### ISSUE TITLE
fields中使用render，弹窗不显示对应字段

### ISSUE THREAD

**Issue by niyg** [viewweiwu/amiya#87]
如图：
![image](https://user-images.githubusercontent.com/14817820/200771212-dda92ebe-24a3-430c-ad84-adb5427531c7.png)
![image](https://user-images.githubusercontent.com/14817820/200771269-c61591cb-cfca-4805-830e-29149eb2f403.png)
添加render参数后，在弹窗中就不会显示这个字段了。

**Comment by niyg** [comment]
![image](https://user-images.githubusercontent.com/14817820/200773175-78589234-45ea-401d-93e2-951d15e20434.png)
看了下你源码部分对于这部分的处理，render我更多是想作用与表格，不应该作用在弹窗上。

**Comment by niyg** [comment]
成功使用renderType的方式跳过使用render了。避免出现弹窗中不显示的问题。

**Comment by viewweiwu** [comment]
render 会影响里面如果只需要弹窗里面有，请这样写
```js
{
   dialog: {
      render: () => xxx
   }
}
```
只想 table 有，请这样写
```js
{
   table: {
      render: () => xxx
   }
}
```

**Comment by viewweiwu** [comment]
如果直接写在第一层， table 和 dialog 都会有作用的

**Comment by niyg** [comment]
OK， 很棒
