### ISSUE TITLE
表单type:list的时候，有办法给children中的field设置默认值吗

### ISSUE THREAD

**Issue by niyg** [viewweiwu/amiya#92]
![image](https://user-images.githubusercontent.com/14817820/204191468-2c0faa9f-a1b9-484d-888a-8ca49c3a4fda.png)
目前结果，没生效

**Comment by viewweiwu** [comment]
<img width="438" alt="image" src="https://user-images.githubusercontent.com/14287892/204572949-8f7aeac6-e48e-4b30-b023-1fc739fed7cf.png">
