### ISSUE TITLE
searchTable中，如何设置表单项的addonAfter

### ISSUE THREAD

**Issue by niyg** [viewweiwu/amiya#97]
![image](https://user-images.githubusercontent.com/14817820/211755687-ce3592c1-d31f-492d-86a5-46e925fd2ea6.png)
我想要的效果是这样的

**Comment by viewweiwu** [comment]
是放在新增里面吗

**Comment by viewweiwu** [comment]
直接写呀

**Comment by viewweiwu** [comment]
```ts
const fields = [
  {
    title: 'hello',
    dialog: {
      addonBefore: 'before',
      addonAfter: 'after'
    }
  }
]
```

**Comment by viewweiwu** [comment]
如果是 form，直接这样写
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/14287892/211765376-50b6bcfe-0151-43db-8a7f-d0b9e9a89065.png">
